### ISSUE TITLE
line 67: md5_gnu: command not found 

### ISSUE THREAD

**Issue by onlinegill** [Lednerb/vestacp-backup-manager#3]
Hello When i try to run it shows fowlloing error 
 ./backup.sh: line 67: md5_gnu: command not found
07:05:45 >>>>> MD5-Hash is invalid, deleting local file...

**Comment by Lednerb** [comment]
Hello,
it seems that the problem occurs because md5_gnu is not installed on your server.

However, this project is deprecated. I cannot recommend using this script.
Just have a look at the duplicity and duply (an easy to use interface for duplicity) for easy and secure incremental backups.
